### ISSUE TITLE
Creatre A Readme file according to  hacktober

### ISSUE THREAD

**Issue by sarthaknerd** [sarthaknerd/AmazingPoftfolios#1]

**Comment by Atharv-777** [comment]
hey @sarthaknerd shall i add contribution steps in the readme?

**Comment by sarthaknerd** [comment]
Yes You can go ahead and please star the repo

**Comment by sarthaknerd** [comment]
> hey @sarthaknerd shall i add contribution steps in the readme?

Yes You can go ahead and please star the repo @Atharv-777

**Comment by Atharv-777** [comment]
hey @sarthaknerd can you add a readme file, as I'm unable to fork it. It says "Can't fork as Repo is empty".

**Comment by sarthaknerd** [comment]
> hey @sarthaknerd can you add a readme file, as I'm unable to fork it. It says "Can't fork as Repo is empty".

Added a new Readme File @Atharv-777 . You can also check new issues

**Comment by Atharv-777** [comment]
@sarthaknerd thanks
