### ISSUE TITLE
create a contact me webpage using HTML CSS JS for a Portfolio website

### ISSUE THREAD

**Issue by sarthaknerd** [sarthaknerd/AmazingPoftfolios#4]

**Comment by pulkithanda** [comment]
Hey @sarthaknerd Please assign this issue to me.

**Comment by sarthaknerd** [comment]
@pulkithanda I have assigned 2 issues to you and Please Star the repo .  Connect on LinkedIn @https://www.linkedin.com/in/sarthakranjan/
